apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: hello-world-production

images:
  - name: ghcr.io/ras-km/hello-world
    newTag: v1.0.17

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Rollout
      name: hello-world