apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-credentials
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgAge4kfrQsC9i619g6PfPedKqTNYUh+HZW5EFL9Fct2sirHSmh2KDKXD/6NbaK7jCDkZNHbfeRjrMYaYcLthhUYYwabo/Fcplg0cXl8U+9KL1oz0A7F9fe1tKWT0zaZyr4j0YZvoNyr2gK+9J74AXXD/xkvYwd6V/kJOTFV4tF/1HRwGHihobjDtPwo1egPP07si5Y8o+rDJSqKyhwdtPESIBW6mTMaXIHuAFHeNHuy0LQ53ZtrzcfjdyLeb/PKYbC4WbltfxVFe7ehchlKXIyFrj8kekVWPfbafg9JfDQ7z5JMhUEgruTJzt8pk8RAkoRoen8S/vdLYyJkyH4RGOI/nDZeW/xGMLAacT5bA2ZE/qfSdEBgrsPVuDrUJHE3wOuKiCofz+Ii1Gdir2vtYUC3iMGNhJWY8b/c8J57Gpg4CkqHII7ehBBzHDmv8ZxwNDPNNvdGLWY/6I067PY/0FgfCNwLksYKhv7V4iYUD2U1Dw/H+R2EYzHlTiJta9tiS+iUmVHU6+X0z76Wql8JFyBQrxFcOxHz1vCGOS3kKJKh+CVDBMRYy/R8qdro/XLIdGmSp85cTjh2gvvgSmk41y418gT6P6qyAtst0HY8rzTV1gcYALY28dRvsxFu3fFdLruEj+H7/CAJAzxIjvLRRTt5+Q3dw09MioqfMuR894Djgzx95B5NRP0Wv1URrXmnT/RD15f4n9k4TInHpCggO1ZTPy0w9VpMPMe5j2xQGjrrE6Z8h/FL93ltqpTxdOO9ihRzgzGmgjtcOT4JFrDUBlReRDhjyhzyt+knFKWLAH+jeQBZZSM9jCN3kkN7jke8uXBzulfCk1Al/PHZWRSa8G1C4CWVEVwGIqmxm7/dzO8fpbhiDj1hBomz1R4qlxQjXXK8xiS///FuqcAwpvHzvV7761p7YlRL0U4rqsM=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-credentials
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
---
