apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-credentials
  namespace: argocd
spec:
  encryptedData:
    .dockerconfigjson: AgBThGpg2bXlBUYhwFbCpj3H+pZrtAwD5IOCl2mfhxeJTpqQdDgbFnpsS978uOTBWKmjNJ9Ojbj01GpIJpLSJBr7rZv/dlFFpBzIgnqwCGVjSlnObLuZYgc6dxuRdjHKFDPm3NVDKGdDotE/Chwn0Na6jHO2VK766Uoh5Ri8ryhCsgSkGEMdqkzh8SI09FQ+aZNt+EGsQ631a6uE5YItJEv81OMi539kpigU4QOpVDcrZBimKpAUGkCTJV7/9IOhR2Zd5SM/EVO3P5Ka4WUjbfL4SBgD7VIPdT89cHKEMDPTGj8edJH6Sn1risvaQWMPmsId/akTEEblizhz8NTcfp3h3iTtSYXab15rvOcqFd3VwfTG8nn5hq+vXm1M4h29CKXuH8LtpSzaHx4wNm6Ttr8DZLlV3j369IvNRc7RluR7Q/a/zJIO7MKff55ZFEZrAOYRDugkaiR5zuHWq4wIHleGMgFuyEPfCpjuPD6QZAL9SQthcjAS5UpdDYv1VdpRpupVk+/c2sbdSHG0MzpLvzGlqu1gpKMo1Br6j0CNFlQ6rKXhDG0emVNrBW2fVjzPUtXx2QBeRqKHbEAzJ/TzSSAFvRf3JgiATLfxyRoymzJzU5EVWgptxS2ycQMihBC1Q4fDahYWyLqzBFAhpJY7zkToOq+qcqPwHWJyCX4uQqMG12DdEvN2Pf0/38GIlNSKrC9M4YeFdEyb9KjlYlUJSpiVyqV7YbcUIwtjWSyQE3l2a88Ys1K/gHOZTzBQWQXuhE7yDmxlnVB+totV/KOH0iOuCKDZsyEFP0XsdJWmULSdXOd2zA68olHgahBeT2U0pat3Ypro/YfhdguvhPkHY+6DH62yHB6ilK7knJUldmVec4Ypk2oxvFFLHf5gTWNqMDVDdqw0qDVGbZyfeRbPSffTHlCQGpWN/ywaMlo=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-credentials
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
---
