apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-world-secret
  namespace: hello-world-production
spec:
  encryptedData:
    APP_SECRET: AgBH9M0GmwGbCmVDHqpJev2SyKMXYUGPO6ZhPyZlvNBTsT4KB5D/YKB9uncZfJ4zF0bHok87DSKQepc737OYIibfhdM0TPQNkDwTE6YJPJb11tpm8uW5ncZ8mCnDHnVTky5qM3Ybuyhp7NutzohcERrfa0kTEumM6RjOIIXjDnf4j0VJqPN9QvRX/m83HLyAf6UA6/ZIclPdAC5MYOZiNgWEp7QDrSrSruzeT2Eis/t9XaG2Sfuu15dy/8JkV2tPhw1Lb6jPtcY4jf9WvfwD/m1rmojP9jh0mShTM3j8vpBUTRgBPK9TfaCElXsaCWG1zgt7xc4jkHA5/FO//YoX1dc86RnHvpLOW8o1TRQ3iu2LHNvaWja8E4Pxdz3hWyMuYCvzckZ+/KAaK9e2Gxxypzd6Ts92EGb3Or2TmM+1nh/Bm7+me4+gUi3F0juyWuowxBX+zxHeMgxfOV/nyPJhOiPObrWYl6bkNgVeRw4sZ2wNcAN0+ICyFHYV8izgiYgo89a0Sfc2tKT9YcyRsZPf4u/feWLHNfMKNiGwesnaSkgZsyN/WvYBEh5v6FMsAzfO7OfhG9e8fssTM0vLSvxgM1ylIrLEO84NlJ/qmOw60RiAWLTgGReYl5klAwBZnP9iYe2nLiFwQOqSRL9tFg55CTSUbjgsYFx7EdQKyccBK5WT4siTg1tDOBD1yg3ijfkF8OkLm9tmLKbDoPOCh0f26yml0NI=
  template:
    metadata:
      creationTimestamp: null
      name: hello-world-secret
      namespace: hello-world-production
---
