apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-world-secret
  namespace: hello-world-production
spec:
  encryptedData:
    APP_SECRET: AgAc/e7DScwaJE2+WbFPFH4pqPLdiSd2TPRLqsDmFrIPr9t4SLnw05gx+yC5+CWTp+sx+5pfm+nQFs33qUsnKSBc1PWDgS7F6/3k74BYJW2FMfVEa5H44GYUjtg6ws/IDW2K7ecTeh2Jayy1DjW10vcwsBBDACYbFETJut32qdKHg8WOFCX3zwV/E0De9lFNyGf2irNojHyYYGz4X/gvzwax7ObemrSGpJ6GcB8mzaXmFFB4UYWXokJNn5ZGN32OYV9+/1kP6dIjlOh6cdeo/lE4W4NNYUpk1dyHMZFmYi54X1G+Irwhx1FBqaXEWvc21rDp5LrXFigqjII6RQIAHXg3tsDp81C02tblbCThiyrqPum7DhZPIw/+jtvgc1zIM7huK6J9nO4fE0Giz+0z9k6oIj//aBNvsqKlSkeIBm+CNnjP6ByDawv0fF1U8b8MAojgfeNFVleGf4kTle9TWZVncZwL9T5Z1DEVW6atwcfBjeGQGk6DogtD8cyB+zk7IK4Ww+0lmHgksjkzNpOsFacSHerrHexbVhH+eJErrfycGJyreAGRm2RQgV8V9gCeZ/2ceDncEPxjNhmJGBOx+ureuDRRrNMaguU6swaB9udXlDcFJJ/GMAQ96KLrGUKFGffy+fTpFGwg//zWrWbyZEpMSW4IKGWH5B1VOO+clmrye8KvmbslWT0URtMimHHUBNfEY8uwyzPXWuOr6PZw/cL85NM=
  template:
    metadata:
      creationTimestamp: null
      name: hello-world-secret
      namespace: hello-world-production
---
