apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - services-blue-green.yaml
  - ingress.yaml
  - servicemonitor.yaml

commonLabels:
  managed-by: argocd
  team: platform