apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Enable Kustomize Helm plugin
  kustomize.buildOptions: "--enable-helm"
  # Enable resource tracking
  application.resourceTrackingMethod: annotation
  # Repo server timeout (increase for large repos)
  timeout.reconciliation: 180s
