apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-egressgateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.23.0
    helm:
      values: |
        service:
          type: ClusterIP
        labels:
          app: istio-egressgateway
          istio: egressgateway
        serviceAccount:
          name: istio-egressgateway
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true