apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.89.0
    helm:
      values: |
        auth:
          strategy: anonymous
        kiali_feature_flags:
          disabled_features: []
        external_services:
          prometheus:
            url: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          grafana:
            enabled: true
            in_cluster_url: http://monitoring-grafana.monitoring.svc.cluster.local:80
            url: http://monitoring-grafana.monitoring.svc.cluster.local:80
            auth:
              type: basic
              username: admin
              password: changeme123
          tracing:
            enabled: false
        server:
          web_root: /kiali
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true